// Random C code generated by AI Assistant
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    srand(time(NULL));
    int x = rand() % 10;
    if (x > 5) {
        printf("Number is greater than 5\n");
    } else {
        printf("Number is less than or equal to 5\n");
    }
    return 0;
}
